### ISSUE TITLE
Some markers cause error message

### ISSUE THREAD

**Issue by donovanhide** [ripple/rippled-historical-database#81] opened 2015-08-15 15:33 UTC
```
curl -s 'http://data.ripple.com/v2/exchanges/XRP/USD+rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q/?limit=1000&descending=true&reduce=false&marker=USD|rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q|XRP||20150722162140|000014793416|00003|00003'
{"result":"error","message":"unable to retrieve exchanges"}
```

Pages of results with earlier markers work, so I'm guessing there is a transaction within the group of 1000 before `USD|rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q|XRP||20150722162140|000014793416|00003|00003` that is causing a problem.

**Comment by donovanhide** [comment] 2015-08-15 15:50
Another example:

```
$ curl -s 'http://data.ripple.com/v2/exchanges/XRP/USD+rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B/?limit=1000&descending=true&reduce=false&marker=USD|rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B|XRP||20150601203100|000013797162|00073|00005'
{"result":"error","message":"unable to retrieve exchanges"}
```

**Comment by shekenahglory** [comment] 2015-08-17 17:29
This is actually caused by a bug with hbase involving their reversed index
scanning - should be fixed when we upgrade hbase I'm told.  But until then
its best to use descending=false if you can.  It happens sporadically, and
sometimes you can retry the same query at a later date and it will work.
the one above still does not though

**Comment by professorhantzen** [comment] 2016-12-26 23:40
Possibly related:  https://github.com/ripple/rippled-historical-database/issues/129

However, this issue explicitly includes "descending=false" and still generates an error.

**Closed** 2018-10-17 17:18 UTC
